### ISSUE TITLE
Compiling on a Mac: clang: error: unsupported option '-static-libgcc'

### ISSUE THREAD

**Issue by torntrousers** [nyumaya/nyumaya_audio_recognition_lib#2]
When building on a Mac I get this error:
```
[ 51%] Linking CXX shared library libnyumaya.dylib
clang: error: unsupported option '-static-libgcc'
make[2]: *** [libnyumaya.dylib] Error 1
make[1]: *** [CMakeFiles/nyumaya.dir/all] Error 2
make: *** [all] Error 2
```
According to https://stackoverflow.com/questions/19649634/clang-error-unsupported-option-static-libgcc-on-mac-osx-mavericks on a Mac the option should be removed, which I've tried and it now gets further:
```
git diff CMakeLists.txt
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 001a220..6ecefab 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -165,7 +165,7 @@ add_library(nyumaya SHARED ${SOURCES} lib.cpp AudioRecognitionImpl.cpp feature_e
 add_executable(benchmark  ${SOURCES}  ${BENCHMARK_SOURCES})

 target_link_libraries(nyumaya Threads::Threads)
-target_link_libraries(nyumaya m  -static-libgcc -static-libstdc++ )
+target_link_libraries(nyumaya m -static-libstdc++ )
```

**Comment by yodakohl** [comment]
I had the static lib for compability reasons. Can we include a check to do this only on mac?
https://stackoverflow.com/questions/9160335/os-specific-instructions-in-cmake-how-to

if(APPLE)
   target_link_libraries(nyumaya m -static-libstdc++ )
else
   target_link_libraries(nyumaya m  -static-libgcc -static-libstdc++ )
endif()
